--评价系统部门表

CREATE TABLE RELEVANCE 
(
	RELEVANCE_ID   VARCHAR2(30)      NOT NULL,
	USER_ID        VARCHAR2(30)      NOT NULL,
	RELEVANCE_NAME VARCHAR2(30)      NOT NULL,
	UPDATE_TIME   DATE              NULL,
	UPDATE_USER   VARCHAR2(36)      NOT NULL,
	RE_NUMBER	  VARCHAR2(10)      NOT NULL,
	CONSTRAINT RELEVANCE_PK PRIMARY KEY 
    (RELEVANCE_ID)
    ENABLE 
);

COMMENT ON TABLE  RELEVANCE             IS '部门表';
COMMENT ON COLUMN REVIEW_USER.USER_ID   IS '用户ID';
COMMENT ON COLUMN REVIEW_USER.RELEVANCE_ID   IS '部门ID';
COMMENT ON COLUMN REVIEW_USER.RELEVANCE_NAME IS '部门名称';
COMMENT ON COLUMN DEPARTMENT.UPDATE_TIME   IS '更新时间';
COMMENT ON COLUMN DEPARTMENT.UPDATE_USER   IS '更新人';
COMMENT ON COLUMN DEPARTMENT.RE_NUMBER   IS '部门编号';
